레이저가 특정 영역에서만 보이도록 한다.
LazoYoung/EcoDiver pull request #77
Opened 2024-05-12 06:30 UTC by Invidam

# 변경사항
특정 영역 들어가면 Ray 켜짐
특정 영역 나가면 Ray 꺼짐

# 진행사항
1. XR Origin 태그에 Player 추가.
2. RayZone 생성 후 IsTrigger True 로 변경

2024-05-12 11:44 UTC, LazoYoung commented
테스트 가능한 씬이 있나요?

2024-05-12 11:58 UTC, Invidam commented
> 테스트 가능한 씬이 있나요? RayZone 안에서만 레이저가 보이도록 하는건가요?

1. `CollectTestScene` 에서 작업했습니다 깜빡했네요.
2. 특정 영역에서만 레이저가 보이는 것 맞습니다

추가로 이전 작업 #73 이 dev를 안거치고 main으로 갔고, 이로 인해 커밋들이 합쳐졌어요
앞으로는 뭐든 dev를 거쳐 main으로 가야할 것 같아요

2024-05-12 12:32 UTC, LazoYoung commented
네 익일까지 확인해보겠습니다.
그리고 main으로 합칠 시기에 대한 모호함이 있는 것 같아요. 디자인팀이 메인에 합치는 주기는 보통 2~3주에 한 번인데 그때까지 dev에 쌓아놓고만 있는것도 바람직하지 않다고 생각되어요.

2024-05-13 10:02 UTC, LazoYoung commented on Assets/Script/Interaction/RayZoneTrigger.cs
> +            if (other.CompareTag("Player"))
![image](https://github.com/LazoYoung/EcoDiver/assets/9482578/32e89dc7-cafc-469a-b27b-8af0127b06bf)

XR Physics 프리팹 기준으로 Collider 컴포넌트 위치가 변경되었고 따라서 트리거가 작동하지 않습니다.
`GetComponentInParent<XROrigin>()` 으로 Collider가 플레이어인지 여부를 판단하는 게 어떨까요?

2024-05-13 10:03 UTC, LazoYoung requested changes
오래된 버전의 XR Interaction Setup 프리팹을 사용하는 것으로 확인됩니다.
XR Physics 최신 프리팹에 대응하도록 수정 부탁드립니다.

2024-05-14 13:48 UTC, Invidam commented
수정했어요 `CollectTestScene` 에서 확인가능하고

```diff
+ `XR Physics/XR Origin/Body Collider`의 IsTrigger, Player Tag 추가
- XR Origin 태그에 Player 추가.
```
이밖의 내용은 기존과 동일합니다.

dev로 머지되면 MainScene에도 반영할게요

2024-05-14 13:48 UTC, Invidam commented
> 오래된 버전의 XR Interaction Setup 프리팹을 사용하는 것으로 확인됩니다. XR Physics 최신 프리팹에 대응하도록 수정 부탁드립니다.

@LazoYoung 
수정했어요 `CollectTestScene` 에서 확인가능하고

```diff
+ `XR Physics/XR Origin/Body Collider`의 IsTrigger, Player Tag 추가
- XR Origin 태그에 Player 추가.
```
이밖의 내용은 기존과 동일합니다.

dev로 머지되면 MainScene에도 반영할게요

2024-05-14 14:17 UTC, Invidam commented
[영역에 따라 오브젝트 On Off
](https://github.com/LazoYoung/EcoDiver/wiki/%EC%98%81%EC%97%AD%EC%97%90-%EB%94%B0%EB%9D%BC-%EC%98%A4%EB%B8%8C%EC%A0%9D%ED%8A%B8-On-Off) 에 문서화했어요.

> [!IMPORTANT]
> 추가로 이후 커밋들은 내용이 변한 게 아니라 범용적으로 활용(Ray뿐만 아니라 추후 다른 곳에서도 사용)하기 위해 변수 명 수정, 확장성만 고려했어요.

2024-05-14 23:22 UTC, LazoYoung approved these changes

2024-05-15 06:56 UTC, merged