페이드 인 앤 아웃
LazoYoung/EcoDiver pull request #87
Opened 2024-05-15 13:18 UTC by Invidam

페이드 인 앤 아웃을 적용했습니다.

결과: 
![Screen Recording 2024-05-15 at 10 12 18 PM](https://github.com/LazoYoung/EcoDiver/assets/71889359/67dd530a-0f50-4ede-a4b1-530c4e00a405)

(렉땜에 천천히 보임)

# 테스트
테스트 가능한 씬 :`Experiment/Test/StartScene.unity`
테스트 방법: PC기준 탭 두번 후 N버튼 클릭

![image](https://github.com/LazoYoung/EcoDiver/assets/71889359/e3610120-87e1-4add-b321-c12a9b97ecf9)
(클릭 하기)

# UI와 연동
현재에 적용된 건 없고 다음 UI 작업에 진행하겠습니다.

# 프로덕션에 적용
- 씬을 테스트하는 거라, 프로덕션 적용하긴 꽤 까다로워 보입니다. 일단 프로덕션 / 테스트 씬을 선택할 수 있게는 만들었어요
- (1) 제가 (2) 여러 프로덕션 씬이 생기면 (3) 프로덕션 씬을 조회하고 이동할 수 있게 수정할게요
  - 예상 순서: 씬 추가, `SceneDetails` 객체 Name 변경, 빌드 설정에 씬 추가
# 변경사항들
- 새로운 테스트 씬
- Build Data 수정 (다음 씬 선택 위해서)
 
## 프리맵 변경
### XR Physics
Fade Screen을 추가함.
- XR Physics - XR Origin - Camera Offset - Main Camera - Fade Screen 오브젝트 추가
- 목적: 사용자 눈을 가리는 용도.

### Game Systems
SceneManager을 추가함.
- Scene - SceneManagaer 오브젝트 추가.
- 목적: 씬 이동

# 문서 링크
https://github.com/LazoYoung/EcoDiver/wiki/Fade-In---Out

2024-05-15 13:57 UTC, LazoYoung commented on Assets/Script/Scene/SceneManager.cs
> +namespace Scene
namespace가 잘못되었습니다.

2024-05-15 13:57 UTC, LazoYoung commented on Assets/Script/Scene/SceneDetail.cs
> +namespace Scene
namespace가 잘못되었습니다

2024-05-15 13:57 UTC, LazoYoung commented on Assets/Script/Scene/FadeScreen.cs
> +namespace Scene
namespace가 잘못되었습니다

2024-05-15 14:25 UTC, LazoYoung requested changes

2024-05-15 14:25 UTC, LazoYoung commented on Assets/Script/Scene/SceneManager.cs
> +                Debug.LogWarning("Fade Screen is not set.");
![image](https://github.com/LazoYoung/EcoDiver/assets/9482578/9ef67fb2-4ee2-4a0b-84db-8952858647c7)

SceneManager.cs:65 라인에 `Debug.Log("Fade screen found.");` 구문을 추가 후 테스트했습니다.
씬을 전환하면 SceneManager.cs:61 라인과 :65 라인이 모두 실행됩니다.
기존 씬에 배치된 오브젝트와 새로운 씬 오브젝트가 동시에 중복 Awake 된 것으로 보입니다.
스크립트 인스턴스가 중복 생성되지 않도록 기존 오브젝트 혹은 스크립트를 비활성화하는 작업이 필요할 것 같습니다.

2024-05-15 14:33 UTC, LazoYoung commented on Assets/Script/Scene/SceneManager.cs
> +        private static bool IsExistInScenario(List<SceneDetail> sceneDetails,
(advice) Exist는 동사이므로 Does ... Exist ? 가 맞는 문법입니다

2024-05-15 14:41 UTC, LazoYoung commented on Assets/Script/Scene/SceneManager.cs
> +                Debug.LogError("Current scene is not exist in scenario");
(Same as above) Current scene does not exist in scenario

2024-05-16 01:38 UTC, LazoYoung commented on Assets/Script/Scene/SceneManager.cs
> +                Debug.LogWarning("Fade Screen is not set.");
https://unity.com/resources/level-up-your-code-with-game-programming-patterns

PDF 57p를 보면 Lazy Instantiation과 `DontDestroyOnLoad()` 를 사용해서 씬 전환에도 강건한 싱글톤 인스턴스 구현법이 있으니 참고해도 좋을 것 같습니다.

2024-05-17 02:16 UTC, Invidam commented on Assets/Script/Scene/SceneManager.cs
> +                Debug.LogWarning("Fade Screen is not set.");
이런 자료는 어떻게 찾았어요..??;;

2024-05-17 02:43 UTC, LazoYoung commented on Assets/Script/Scene/SceneManager.cs
> +                Debug.LogWarning("Fade Screen is not set.");
Googling ;)

2024-05-17 03:22 UTC, Invidam commented on Assets/Script/Scene/FadeScreen.cs
> +namespace Scene
3371e6a 👍

2024-05-17 03:22 UTC, Invidam commented on Assets/Script/Scene/SceneDetail.cs
> +namespace Scene
3371e6a 👍

2024-05-17 03:24 UTC, Invidam commented on Assets/Script/Scene/SceneManager.cs
> +                Debug.LogError("Current scene is not exist in scenario");
ed37a6c 반영했어요~

2024-05-17 03:25 UTC, Invidam commented on Assets/Script/Scene/SceneManager.cs
> +        private static bool IsExistInScenario(List<SceneDetail> sceneDetails,
705d559 반영!

2024-05-17 03:31 UTC, Invidam commented on Assets/Script/Scene/SceneManager.cs
> +                Debug.LogWarning("Fade Screen is not set.");
7cad313 에 수정했어요!!

싱글톤 방식이 제가 원래 원하던 방식이기도 하고 좀 더 강건해보입니다

다만 기존 방식이 `씬을 1번 전환하면 SceneManager.cs:61 라인과 :65 라인이 모두 실행됩니다. (씬을 N번 전환하면 N번 출력됩니다.)
기존 씬에 배치된 오브젝트와 새로운 씬 오브젝트가 동시에 중복 Awake 된 것으로 보입니다.` 라고 해주셨는데

확인해보니 **다른 오브젝트에도 스크립트가 중복 적용되고 있었고** 기존 씬과 새로운 씬의 Awake가 모두 실행된 건 아니었어요 앞으론 주의할게요~ 😅

2024-05-17 04:23 UTC, LazoYoung approved these changes
수고하셨습니다~

2024-05-18 09:44 UTC, merged